import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.105.0";
const origins=new Set(["https://astraoilandgas2026.github.io","http://localhost:5500","http://127.0.0.1:5500"]);
const cors=(req:Request)=>{const o=req.headers.get("Origin")??"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"null","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}};
const json=(body:unknown,status:number,h:any)=>new Response(JSON.stringify(body),{status,headers:{...h,"Content-Type":"application/json"}});
Deno.serve(async(req)=>{
 const h=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers:h});if(req.method!=="POST")return json({error:"Method not allowed"},405,h);
 const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return json({error:"Authentication required"},401,h);
 const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});
 const {data:userData,error:authError}=await db.auth.getUser(auth.slice(7));
 if(authError||!userData.user)return json({error:"Invalid authentication"},401,h);
 const key=Deno.env.get("ELEVENLABS_API_KEY");if(!key)return json({error:"ELEVENLABS_NOT_CONFIGURED"},503,h);
 let body:any;try{body=await req.json()}catch{return json({error:"Invalid JSON"},400,h)}
 const text=String(body.text||"").trim();let voiceId=String(body.voice_id||Deno.env.get("EMMA_ELEVENLABS_VOICE_ID")||"").trim();const modelId=String(body.model_id||"eleven_flash_v2_5");
 if(body.setup_voice){
  const adminKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if(!voiceId&&adminKey){const db=createClient(Deno.env.get("SUPABASE_URL")!,adminKey);const {data}=await db.from("jarvis_global_context").select("content").eq("context_key","emma.voice_id").eq("active",true).maybeSingle();voiceId=String(data?.content||"").trim();}
  if(!voiceId){const description="Distinctive adult female AI assistant, late 20s to early 30s. Medium-low pitch with warm rich chest resonance and a subtle natural husky rasp. Crisp diction, energetic conversational pace, intelligent, confident, observant, mischievous and witty. Dry humor and precise comedic timing. Can sound amused, skeptical, mildly exasperated, focused, authoritative or genuinely excited. Never sugary, submissive or robotic. Professional and precise in business; playful and teasing in casual conversation. Neutral American English and neutral Latin American Spanish with the same identity. Human, charismatic, futuristic but natural. Original voice identity.";const design=await fetch("https://api.elevenlabs.io/v1/text-to-voice/design",{method:"POST",headers:{"xi-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({model_id:"eleven_multilingual_ttv_v2",voice_description:description,text:"Okay, give me a second. I am checking the numbers now. Then I will tell you exactly what matters."})});if(!design.ok)return json({error:"ELEVENLABS_VOICE_DESIGN_FAILED",detail:(await design.text()).slice(0,500)},design.status,h);const designed=await design.json();const generatedVoiceId=String(designed?.previews?.[0]?.generated_voice_id||"").trim();if(!generatedVoiceId)return json({error:"ELEVENLABS_VOICE_DESIGN_EMPTY"},502,h);const created=await fetch("https://api.elevenlabs.io/v1/text-to-voice",{method:"POST",headers:{"xi-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({voice_name:"Emma Astra",voice_description:description,generated_voice_id:generatedVoiceId})});if(!created.ok)return json({error:"ELEVENLABS_VOICE_CREATE_FAILED",detail:(await created.text()).slice(0,500)},created.status,h);const createdData=await created.json();voiceId=String(createdData?.voice_id||"").trim();if(!voiceId)return json({error:"ELEVENLABS_VOICE_CREATE_EMPTY"},502,h);if(adminKey){const db=createClient(Deno.env.get("SUPABASE_URL")!,adminKey);await db.from("jarvis_global_context").upsert({context_key:"emma.voice_id",content:voiceId,importance:10,active:true,updated_at:new Date().toISOString()},{onConflict:"context_key"});}}
  return json({ok:true,configured:Boolean(voiceId),provider:"elevenlabs",model:"eleven_flash_v2_5"},200,h);
 }
 if(text.length<1||text.length>5000||!voiceId)return json({error:voiceId?"text required":"EMMA_ELEVENLABS_VOICE_ID not configured"},400,h);
 const r=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}/stream?output_format=mp3_22050_32`,{method:"POST",headers:{"xi-api-key":key,"Content-Type":"application/json","Accept":"audio/mpeg"},body:JSON.stringify({text,model_id:modelId,language_code:body.language_code==="en"?"en":"es",voice_settings:{stability:0.42,similarity_boost:0.82,style:0.62,use_speaker_boost:true,speed:1.08}})});
 if(!r.ok)return json({error:"ELEVENLABS_TTS_FAILED",detail:(await r.text()).slice(0,500)},r.status,h);
 const bytes=new Uint8Array(await r.arrayBuffer());
 let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));
 return new Response(bytes,{status:200,headers:{...h,"Content-Type":"audio/mpeg","Cache-Control":"no-store"}});
});