import { createClient } from "https://esm.sh/@supabase/supabase-js@2.105.0";
import { CONFIG } from "./config.js";
import { createOrb } from "./modules/orb.js";
import { createVoice } from "./modules/voice.js";
import { detectModule, getModules } from "./modules/router.js";
import { getTool } from "./core/tool-registry.js";
import { classifyIntent } from "./core/intent-router.js";
const supabase=createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey,{auth:{experimental:{passkey:true}}}),$=s=>document.querySelector(s);
const authPanel=$("#auth-panel"),workspace=$("#workspace"),logout=$("#logout"),install=$("#install"),status=$("#auth-status"),connection=$("#connection"),command=$("#command"),result=$("#result"),transcript=$("#transcript"),moduleTitle=$("#module-title"),moduleContent=$("#module-content"),modulesNav=$("#modules");
const orb=createOrb({root:$("#orb"),status:$("#orb-status"),onActivate:()=>voice.start()});const modules=getModules();let activeModule="astra";let deferredInstall=null;
function renderModules(){modulesNav.innerHTML="";Object.entries(modules).forEach(([key,m])=>{const b=document.createElement("button");b.textContent=m.label;b.dataset.module=key;b.className=key===activeModule?"active":"";b.onclick=()=>selectModule(key);modulesNav.appendChild(b)})}
function selectModule(key){activeModule=key;moduleTitle.textContent=modules[key].label;moduleContent.innerHTML="<p class='module-description'>"+modules[key].description+"</p>";modulesNav.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.module===key))}
function renderSession(session){const signed=Boolean(session?.user);authPanel.classList.toggle("hidden",signed);workspace.classList.toggle("hidden",!signed);logout.classList.toggle("hidden",!signed);connection.textContent=signed?"ONLINE":"OFFLINE";connection.classList.toggle("online",signed);if(signed){$("#command-line").textContent="Núcleo conectado. ¿Qué hacemos?";selectModule(activeModule)}}
async function passkeyLogin(){status.textContent="Esperando biometría...";if(!window.PublicKeyCredential){status.textContent="Este dispositivo/navegador no soporta passkeys.";return}const{error}=await supabase.auth.signInWithPasskey();status.textContent=error?error.message:""}
async function registerPasskey(){const{data:{session}}=await supabase.auth.getSession();if(!session){status.textContent="Primero necesitas una sesión inicial para registrar la huella.";return}status.textContent="Registrando este dispositivo...";const{error}=await supabase.auth.registerPasskey();status.textContent=error?error.message:"Dispositivo registrado. La próxima entrada será con biometría."}
async function execute(text){const q=text.trim();if(!q)return;transcript.textContent="› "+q;const intent=classifyIntent(q);const target=intent.module||detectModule(q);selectModule(target);if(target!=="astra"){result.textContent="Módulo detectado: "+modules[target].label+"\n\nArquitectura preparada. Las herramientas se activarán progresivamente.";return}const tool=getTool("astra.search_supplier");if(!tool?.functionName){result.textContent="Tool no disponible.";return}orb.setState("thinking");result.textContent="Consultando "+tool.label+"...";try{const{data,error}=await supabase.functions.invoke(tool.functionName,{body:{q,limit:10}});if(error)throw error;result.textContent=JSON.stringify(data,null,2)}catch(e){result.textContent="Error: "+e.message}finally{orb.setState("idle")}}
const voice=createVoice({orb,onTranscript:t=>{command.value=t;execute(t)},onError:e=>{transcript.textContent="Voice: "+e}});
$("#passkey").onclick=passkeyLogin;$("#register-passkey").onclick=registerPasskey;logout.onclick=()=>supabase.auth.signOut();$("#execute").onclick=()=>execute(command.value);command.onkeydown=e=>{if(e.key==="Enter")execute(command.value)};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;install.classList.remove("hidden")});install.onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;install.classList.add("hidden")};window.addEventListener("appinstalled",()=>install.classList.add("hidden"));
supabase.auth.onAuthStateChange((_event,session)=>renderSession(session));const{data:{session}}=await supabase.auth.getSession();renderModules();selectModule(activeModule);renderSession(session);if(!session)status.textContent="Activa Jarvis con la huella del dispositivo.";if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
