import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const origins=new Set(["https://astraoilandgas2026.github.io","http://localhost:5500","http://127.0.0.1:5500"]);
const cors=(req:Request)=>{const o=req.headers.get("Origin")??"";return {"Access-Control-Allow-Origin":origins.has(o)?o:"null","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}};
const json=(x:any,status=200,h:any)=>new Response(JSON.stringify(x),{status,headers:{...h,"Content-Type":"application/json"}});
const score=(o:any)=>{const ret=Number(o.expected_return_pct)||0,win=Number(o.win_rate_pct)||0,risk=Number(o.risk_pct)||0,capital=Number(o.capital_required)||0,evidence=Math.max(0,Math.min(100,Number(o.evidence_score)||0)),effort=Math.max(0,Math.min(100,Number(o.effort_score)||0));const edge=Math.max(0,ret*Math.max(win,1)/100),ra=edge/(1+Math.max(risk,0)/10),penalty=capital>0?Math.min(30,Math.log10(capital+1)*8):0,s=Math.max(0,Math.min(100,ra*3+evidence*.35+(100-effort)*.1-penalty));return {score:Number(s.toFixed(2)),expected_value_pct:Number(edge.toFixed(4)),risk_adjusted_edge:Number(ra.toFixed(4)),decision:s>=75?"PROMOTE":s>=55?"EXPERIMENT":"REJECT"}};
async function authorized(req:Request){
 const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))throw new Error("Authentication required");
 const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});
 const {data:u,error:ae}=await db.auth.getUser();if(ae||!u.user)throw new Error("Invalid authentication");
 const {data:ok,error:re}=await db.rpc("emma_is_authorized");if(re||ok!==true)throw new Error("Forbidden");
 return {db,user:u.user};
}
Deno.serve(async req=>{const h=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers:h});if(req.method!=="POST")return json({error:"Method not allowed"},405,h);try{const {db,user}=await authorized(req);let b:any;try{b=await req.json()}catch{return json({error:"Invalid JSON"},400,h)};const tool=String(b.tool||"");if(tool==="money.opportunity.rank"){const items=Array.isArray(b.items)?b.items:[];const ranked=items.map((x:any)=>({...x,ranking:score(x)})).sort((a:any,z:any)=>z.ranking.score-a.ranking.score);return json({ok:true,tool,data:ranked},200,h)}if(tool==="money.opportunity.save"){const x=b.opportunity||{},r=score(x);const {data,error}=await db.from("emma_money_opportunities").insert({user_id:user.id,domain:x.domain||"other",title:String(x.title||"Untitled").slice(0,200),thesis:x.thesis||null,expected_return_pct:x.expected_return_pct||null,win_rate_pct:x.win_rate_pct||null,risk_pct:x.risk_pct||null,capital_required:x.capital_required||null,evidence_score:x.evidence_score||0,effort_score:x.effort_score||0,score:r.score,decision:r.decision,status:"candidate",metadata:x.metadata||{}}).select("*").single();if(error)return json({error:error.message},500,h);return json({ok:true,tool,data},200,h)}if(tool==="money.opportunity.list"){const {data,error}=await db.from("emma_money_opportunities").select("*").eq("user_id",user.id).order("score",{ascending:false}).limit(Math.min(Math.max(Number(b.limit)||20,1),50));if(error)return json({error:error.message},500,h);return json({ok:true,tool,data:data||[]},200,h)}if(tool==="money.outcome.record"){const x=b.outcome||{}, {data,error}=await db.from("emma_money_outcomes").insert({user_id:user.id,opportunity_id:x.opportunity_id||null,strategy_experiment_id:x.strategy_experiment_id||null,capital:x.capital||null,pnl:x.pnl||0,return_pct:x.return_pct||0,max_drawdown_pct:x.max_drawdown_pct||null,outcome:x.outcome||null,metadata:x.metadata||{}}).select("*").single();if(error)return json({error:error.message},500,h);return json({ok:true,tool,data},200,h)}return json({error:"Tool not available"},404,h)}catch(error){const message=error instanceof Error?error.message:"Unknown error";const status=/Authentication|Invalid authentication/.test(message)?401:/Forbidden/.test(message)?403:500;return json({error:message},status,h)}});